import { describe, expect, it } from 'vitest';
import { acceptDesignRevision, acceptImplementationCompletion, acceptRepairCompletion, acceptVerificationOutcome, approveDesignRevision, canCompleteMission, createIntentWorkflowState, guardAgentStageAdmission, guardImplementationAdmission, guardVerificationAdmission, prepareImplementationRepair, startVerification } from './intent-workflow-state.js';
import type { Agent, DesignRevision, Mission, MissionArtifact, MissionTask, TaskAttempt, VerificationRun } from './types.js';

const time = '2026-01-01T00:00:00.000Z'; const hash = 'a'.repeat(64);
const implementationPhases = ['verifying', 'repairing', 'awaiting_intervention', 'completed'];
function mission(phase: Mission['workflow']['phase'] = 'designing'): Mission { const hasImplementation = implementationPhases.includes(phase); return { id: 'mission-1', goal: 'goal', status: phase === 'designing' ? 'running' : 'paused', participants: [{ agentId: 'designer', order: 0, snapshot: { name: 'Designer', description: '', instructions: '', agentUpdatedAt: time } }, { agentId: 'builder', order: 1, snapshot: { name: 'Builder', description: '', instructions: '', agentUpdatedAt: time } }], workflow: { ...createIntentWorkflowState({ designerAgentId: 'designer', builderAgentId: 'builder' }), phase, approvedDesignRevisionId: ['designing', 'awaiting_approval'].includes(phase) ? null : 'design-1', latestDesignRevisionId: phase === 'designing' ? null : 'design-1', implementedWorkspaceRevisionId: hasImplementation ? 'workspace-2' : null }, workspace: { owner: 'conductor', key: 'mission-1', state: 'ready', source: { kind: 'agent_workspace', agentId: 'designer', agentUpdatedAt: time }, currentRevisionId: hasImplementation ? 'workspace-2' : 'workspace-1', revisionStatus: 'clean', nextRevisionSequence: 3 }, currentTaskId: hasImplementation ? null : 'task-1', nextEventSequence: 1, activeRecoveryCommandId: null, tokenBudget: null, createdAt: time, updatedAt: time, startedAt: null, completedAt: phase === 'completed' ? time : null }; }
function task(stage: MissionTask['stage'], bindings: Partial<MissionTask> = {}): MissionTask { return { id: bindings.id ?? 'task-1', missionId: 'mission-1', order: 0, stage, assignedAgentId: stage === 'design' ? 'designer' : 'builder', title: stage, instruction: stage, inputDesignRevisionId: stage === 'design' ? null : 'design-1', inputVerificationRunId: stage === 'repair' ? 'verification-1' : null, inputWorkspaceRevisionId: stage === 'repair' ? 'workspace-2' : 'workspace-1', repairCycle: stage === 'repair' ? 1 : null, status: 'running', authoritativeAttemptId: 'attempt-1', authorityVersion: 1, inputArtifactIds: [], outputArtifactIds: [], outputWorkspaceRevisionId: null, createdAt: time, updatedAt: time, startedAt: time, completedAt: null, ...bindings }; }
function attempt(currentTask: MissionTask): TaskAttempt { return { id: 'attempt-1', missionId: 'mission-1', taskId: currentTask.id, agentId: currentTask.assignedAgentId, attemptNumber: 1, authorityVersion: currentTask.authorityVersion, stage: currentTask.stage, inputDesignRevisionId: currentTask.inputDesignRevisionId, inputVerificationRunId: currentTask.inputVerificationRunId, inputWorkspaceRevisionId: currentTask.inputWorkspaceRevisionId, repairCycle: currentTask.repairCycle, status: 'running', runId: 'run-1', runtimeThreadId: null, inputArtifactIds: [], outputArtifactId: null, outputWorkspaceRevisionId: null, usage: null, error: null, supersededAt: null, supersededByAttemptId: null, startedByRecoveryCommandId: null, createdAt: time, startedAt: time, completedAt: null, updatedAt: time }; }
function revision(): DesignRevision { return { id: 'design-1', missionId: 'mission-1', version: 1, parentRevisionId: null, status: 'draft', sourceTaskId: 'task-1', sourceAttemptId: 'attempt-1', packageArtifactId: 'package', packageHash: hash, previewArtifactId: 'preview', previewHash: hash, contractArtifactId: 'contract', contractHash: hash, feedbackArtifactId: null, createdAt: time, approvedAt: null, supersededAt: null }; }
function verification(status: VerificationRun['status'] = 'running', id = 'verification-1'): VerificationRun { return { id, missionId: 'mission-1', designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2', cycle: id === 'verification-1' ? 0 : 1, status, correlationId: `correlation-${id}`, checks: [], consoleErrors: [], pageErrors: [], url: null, durationMs: null, referenceScreenshotArtifactId: null, actualScreenshotArtifactId: null, reportArtifactId: null, visualDifference: null, error: status === 'error' ? { category: 'infrastructure', message: 'browser unavailable' } : null, createdAt: time, startedAt: null, completedAt: ['passed', 'failed', 'error'].includes(status) ? time : null, updatedAt: time }; }

describe('Intent workflow authority', () => {
  it('requires exact Design authority and pauses for approval', () => { const current = mission(); const currentTask = task('design'); const currentAttempt = attempt(currentTask); expect(guardAgentStageAdmission({ mission: current, task: currentTask, stage: 'design', workspaceRevisionId: 'wrong' })).toEqual({ accepted: false, reason: 'input_binding_mismatch' }); const accepted = acceptDesignRevision({ mission: current, task: currentTask, attempt: currentAttempt, revision: revision(), requiredArtifactsPresent: true, hashesMatch: true }); expect(accepted.accepted).toBe(true); if (accepted.accepted) expect(accepted.value.mission).toMatchObject({ status: 'paused', workflow: { phase: 'awaiting_approval', latestDesignRevisionId: 'design-1' } }); });
  it('rejects stale approval and admits implementation only after exact approval', () => { const current = mission('awaiting_approval'); const draft = revision(); expect(approveDesignRevision({ mission: current, revision: { ...draft, id: 'other' }, requiredArtifactsPresent: true, hashesMatch: true })).toEqual({ accepted: false, reason: 'revision_not_current' }); const approval = approveDesignRevision({ mission: current, revision: draft, requiredArtifactsPresent: true, hashesMatch: true }); expect(approval.accepted).toBe(true); if (approval.accepted) expect(approval.value.phase).toBe('implementing'); });

  it('keeps precheck PASS non-terminal and only final PASS after human acceptance completes', () => {
    const current = mission('implementing');
    const currentTask = task('implement');
    const completed = acceptImplementationCompletion({ mission: current, task: currentTask, attempt: attempt(currentTask), outputWorkspaceRevisionId: 'workspace-2' });
    expect(completed.accepted).toBe(true); if (!completed.accepted) return;
    const precheck = verification('running');
    const started = startVerification({ mission: completed.value.mission, verification: precheck });
    expect(started.accepted).toBe(true); if (!started.accepted) return;
    const precheckOutcome = acceptVerificationOutcome({ mission: { ...completed.value.mission, status: 'running', workflow: started.value }, verification: { ...precheck, status: 'passed' }, implementationAccepted: false, automaticRepairAlreadyUsed: false });
    expect(precheckOutcome.accepted).toBe(true); if (!precheckOutcome.accepted) return;
    expect(precheckOutcome.value.mission).toMatchObject({ status: 'paused', workflow: { phase: 'verifying' } });
    expect(canCompleteMission({ mission: precheckOutcome.value.mission, verification: { ...precheck, status: 'passed' } })).toBe(false);
    const capturedMission = { ...precheckOutcome.value.mission, workspace: { ...precheckOutcome.value.mission.workspace, currentRevisionId: 'workspace-2' } };
    expect(guardVerificationAdmission({ mission: capturedMission, currentVerification: { ...precheck, status: 'passed' }, workspaceState: 'clean' })).toEqual({ accepted: false, reason: 'already_passed' });
    expect(guardVerificationAdmission({ mission: capturedMission, currentVerification: { ...precheck, status: 'passed' }, workspaceState: 'clean', implementationAccepted: true }).accepted).toBe(true);
    const finalRun = verification('running', 'verification-2');
    const finalStarted = startVerification({ mission: precheckOutcome.value.mission, verification: finalRun });
    expect(finalStarted.accepted).toBe(true); if (!finalStarted.accepted) return;
    const finalOutcome = acceptVerificationOutcome({ mission: { ...precheckOutcome.value.mission, status: 'running', workflow: finalStarted.value }, verification: { ...finalRun, status: 'passed' }, implementationAccepted: true, automaticRepairAlreadyUsed: false });
    expect(finalOutcome.accepted).toBe(true); if (!finalOutcome.accepted) return;
    expect(canCompleteMission({ mission: finalOutcome.value.mission, verification: { ...finalRun, status: 'passed' } })).toBe(false);
    expect(finalOutcome.value.mission).toMatchObject({ status: 'paused', workflow: { phase: 'verifying' } });
  });

  it('allows one automatic semantic Repair, then blocks another automatic loop', () => {
    const current = mission('verifying'); current.status = 'running'; current.workflow.currentVerificationRunId = 'verification-1';
    const first = acceptVerificationOutcome({ mission: current, verification: verification('failed'), implementationAccepted: false, automaticRepairAlreadyUsed: false });
    expect(first.accepted).toBe(true); if (!first.accepted) return;
    expect(first.value).toMatchObject({ mission: { status: 'paused', workflow: { phase: 'repairing', repairCycle: 1 } }, repairCycle: 1, requestRepairTask: true });
    const secondMission = mission('verifying'); secondMission.status = 'running'; secondMission.workflow.currentVerificationRunId = 'verification-2'; secondMission.workflow.repairCycle = 1;
    const second = acceptVerificationOutcome({ mission: secondMission, verification: verification('failed', 'verification-2'), implementationAccepted: false, automaticRepairAlreadyUsed: true });
    expect(second.accepted).toBe(true); if (second.accepted) expect(second.value).toMatchObject({ mission: { status: 'blocked', workflow: { phase: 'awaiting_intervention', repairCycle: 1 } }, requestRepairTask: false });
    const priorHumanRepair = mission('verifying'); priorHumanRepair.status = 'running'; priorHumanRepair.workflow.currentVerificationRunId = 'verification-2'; priorHumanRepair.workflow.repairCycle = 1;
    const noLateAutomaticRepair = acceptVerificationOutcome({ mission: priorHumanRepair, verification: verification('failed', 'verification-2'), implementationAccepted: false, automaticRepairAlreadyUsed: false });
    expect(noLateAutomaticRepair.accepted).toBe(true); if (noLateAutomaticRepair.accepted) expect(noLateAutomaticRepair.value).toMatchObject({ mission: { status: 'blocked', workflow: { phase: 'awaiting_intervention', repairCycle: 1 } }, requestRepairTask: false });
  });

  it('keeps verifier infrastructure ERROR retryable and never requests Repair', () => { const current = mission('verifying'); current.status = 'running'; current.workflow.currentVerificationRunId = 'verification-1'; const errored = acceptVerificationOutcome({ mission: current, verification: verification('error'), implementationAccepted: false, automaticRepairAlreadyUsed: false }); expect(errored.accepted).toBe(true); if (errored.accepted) expect(errored.value).toMatchObject({ mission: { status: 'paused', workflow: { phase: 'verifying' } }, requestRepairTask: false }); });

  it('allows only one explicit human implementation Repair from a current passed precheck', () => { const current = mission('verifying'); current.status = 'paused'; current.workflow.currentVerificationRunId = 'verification-1'; const decision = prepareImplementationRepair({ mission: current, verification: verification('passed'), implementationAccepted: false, automaticRepairAlreadyUsed: false, humanRepairAlreadyUsed: false }); expect(decision.accepted).toBe(true); if (!decision.accepted) return; expect(decision.value).toMatchObject({ mission: { status: 'paused', workflow: { phase: 'repairing', repairCycle: 1 } }, repairCycle: 1 }); expect(prepareImplementationRepair({ mission: current, verification: verification('passed'), implementationAccepted: false, automaticRepairAlreadyUsed: false, humanRepairAlreadyUsed: true })).toEqual({ accepted: false, reason: 'repair_limit_reached' }); const exhausted = { ...current, workflow: { ...current.workflow, repairCycle: 2, maxRepairCycles: 2 } }; expect(prepareImplementationRepair({ mission: exhausted, verification: verification('passed'), implementationAccepted: false, automaticRepairAlreadyUsed: false, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'repair_limit_reached' }); });

  it('allows exactly one human Repair after the automatic Repair still fails', () => {
    const current = mission('awaiting_intervention');
    current.status = 'blocked';
    current.workflow.currentVerificationRunId = 'verification-2';
    current.workflow.repairCycle = 1;
    const failedRun = verification('failed', 'verification-2');
    expect(prepareImplementationRepair({ mission: current, verification: failedRun, implementationAccepted: false, automaticRepairAlreadyUsed: false, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'verification_not_passed' });
    expect(prepareImplementationRepair({ mission: current, verification: { ...failedRun, workspaceRevisionId: 'stale-workspace' }, implementationAccepted: false, automaticRepairAlreadyUsed: true, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'verification_not_current' });
    expect(prepareImplementationRepair({ mission: { ...current, workspace: { ...current.workspace, currentRevisionId: 'stale-workspace' } }, verification: failedRun, implementationAccepted: false, automaticRepairAlreadyUsed: true, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'workspace_revision_mismatch' });
    expect(prepareImplementationRepair({ mission: current, verification: failedRun, implementationAccepted: true, automaticRepairAlreadyUsed: true, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'verification_not_passed' });
    const decision = prepareImplementationRepair({ mission: current, verification: failedRun, implementationAccepted: false, automaticRepairAlreadyUsed: true, humanRepairAlreadyUsed: false });
    expect(decision.accepted).toBe(true);
    if (!decision.accepted) return;
    expect(decision.value).toMatchObject({ mission: { status: 'paused', workflow: { phase: 'repairing', repairCycle: 2 } }, repairCycle: 2 });
    const exhausted = { ...current, workflow: { ...current.workflow, repairCycle: 2 } };
    expect(prepareImplementationRepair({ mission: exhausted, verification: failedRun, implementationAccepted: false, automaticRepairAlreadyUsed: true, humanRepairAlreadyUsed: false })).toEqual({ accepted: false, reason: 'repair_limit_reached' });
  });

  it('binds Repair completion to the failed verifier and creates a fresh implementation revision', () => { const current = mission('repairing'); current.workflow.currentVerificationRunId = 'verification-1'; current.workflow.repairCycle = 1; current.currentTaskId = 'task-1'; const repairTask = task('repair'); const repairAttempt = attempt(repairTask); const result = acceptRepairCompletion({ mission: current, task: repairTask, attempt: repairAttempt, outputWorkspaceRevisionId: 'workspace-3' }); expect(result.accepted).toBe(true); if (result.accepted) expect(result.value.mission).toMatchObject({ status: 'paused', workflow: { phase: 'verifying', implementedWorkspaceRevisionId: 'workspace-3', currentVerificationRunId: null } }); });

  it('distinguishes unapproved implementation from a valid protected admission', () => {
    const current = mission('implementing'); current.status = 'paused';
    const approved = { ...revision(), status: 'approved' as const, approvedAt: time };
    const agent: Agent = { id: 'builder', name: 'Builder', description: '', instructions: '', status: 'ready', workspacePath: '/builder', codexThreadId: null, lastError: null, createdAt: time, updatedAt: time };
    const artifacts: MissionArtifact[] = [
      { id: 'package', missionId: current.id, taskId: 'task-1', attemptId: 'attempt-1', kind: 'design_package', mediaType: 'application/json', content: null, storage: { kind: 'external', key: `design-reference-${current.id}-${approved.id}-package` }, sha256: hash, workspaceRevisionId: null, createdBy: { kind: 'system', agentId: null }, originalByteLength: 10, truncated: false, createdAt: time },
      { id: 'preview', missionId: current.id, taskId: 'task-1', attemptId: 'attempt-1', kind: 'design_preview', mediaType: 'text/html', content: null, storage: { kind: 'external', key: `design-reference-${current.id}-${approved.id}-preview` }, sha256: hash, workspaceRevisionId: null, createdBy: { kind: 'system', agentId: null }, originalByteLength: 10, truncated: false, createdAt: time },
      { id: 'contract', missionId: current.id, taskId: 'task-1', attemptId: 'attempt-1', kind: 'design_contract', mediaType: 'application/json', content: null, storage: { kind: 'external', key: `design-reference-${current.id}-${approved.id}-contract` }, sha256: hash, workspaceRevisionId: null, createdBy: { kind: 'system', agentId: null }, originalByteLength: 10, truncated: false, createdAt: time },
    ];
    const currentTask = task('implement', { inputArtifactIds: ['package', 'preview', 'contract'], status: 'pending', authoritativeAttemptId: null, authorityVersion: 0 });
    const facts = { missions: [current], mission: current, tasks: [currentTask], revisions: [approved], revision: approved, task: currentTask, artifacts, workspaceRevision: { id: 'workspace-1', missionId: current.id, sequence: 1, parentRevisionId: null, restoredFromRevisionId: null, snapshotKey: 'revision-00000000-0000-4000-8000-000000000001', contentHash: hash, origin: 'mission_start' as const, boundaries: [{ kind: 'before_task' as const, taskId: currentTask.id }], taskId: currentTask.id, attemptId: null, interventionArtifactId: null, createdBy: 'system' as const, createdAt: time }, workspaceState: 'clean' as const, agent, authoritativeAttempt: null, authoritativeRun: null, attempts: [], measuredTokens: 0 };
    expect(guardImplementationAdmission({ ...facts, mission: { ...current, workflow: { ...current.workflow, approvedDesignRevisionId: null } } }).reason).toBe('approval_missing');
    expect(guardImplementationAdmission({ ...facts, revision: { ...approved, missionId: 'mission-2' } }).reason).toBe('approved_revision_wrong_mission');
    expect(guardImplementationAdmission(facts).accepted).toBe(true);
    expect(guardImplementationAdmission({ ...facts, workspaceState: 'changed' }).reason).toBe('workspace_changed');
  });

  it('shares strict verification admission for first run and ERROR retry while denying semantic FAIL', () => { const current = mission('verifying'); current.status = 'paused'; current.workflow.currentVerificationRunId = null; expect(guardVerificationAdmission({ mission: current, currentVerification: null, workspaceState: 'clean' })).toEqual({ accepted: true, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2' }); const error = verification('error'); current.workflow.currentVerificationRunId = error.id; expect(guardVerificationAdmission({ mission: current, currentVerification: error, workspaceState: 'clean' }).accepted).toBe(true); expect(guardVerificationAdmission({ mission: { ...current, status: 'blocked', workflow: { ...current.workflow, phase: 'awaiting_intervention' } }, currentVerification: { ...error, status: 'failed', error: null }, workspaceState: 'clean' })).toEqual({ accepted: false, reason: 'semantic_failure_blocked' }); expect(guardVerificationAdmission({ mission: current, currentVerification: error, workspaceState: 'changed' })).toEqual({ accepted: false, reason: 'workspace_not_clean' }); });
});
