import { describe, expect, it } from 'vitest';
import type { ImplementationAdmissionView } from './mission-implementation-admission.js';
import { projectMissionProduct } from './mission-presentation.js';
import type { MissionRecoveryCapabilities } from './mission-recovery-policy.js';
import type { Mission, MissionEvent, MissionTask, TaskAttempt, VerificationRun } from './types.js';

const time = '2026-01-01T00:00:00.000Z';
const readyAdmission: ImplementationAdmissionView = { allowed: true, reason: null, message: null };
const unavailableAdmission: ImplementationAdmissionView = { allowed: false, reason: 'wrong_phase', message: 'The Mission is not currently in the Build stage.' };
const recovery = (overrides: Partial<MissionRecoveryCapabilities> = {}): MissionRecoveryCapabilities => ({ retryCurrentDesign: { allowed: false, reason: 'not retryable' }, resumeImplementation: { allowed: false, reason: 'not finalizable' }, retryVerification: { allowed: false, reason: 'not retryable' }, stopPreserving: { allowed: true, reason: null }, verificationAdmission: { accepted: false, reason: 'wrong_phase' }, ...overrides });
function mission(phase: Mission['workflow']['phase'], status: Mission['status']): Mission { const hasImplementation = ['verifying', 'repairing', 'awaiting_intervention', 'completed'].includes(phase); return { id: 'mission-1', goal: 'Build the approved experience', status, participants: [], workflow: { phase, designerAgentId: 'agent-1', builderAgentId: 'agent-1', latestDesignRevisionId: phase === 'designing' ? null : 'design-1', approvedDesignRevisionId: ['designing', 'awaiting_approval'].includes(phase) ? null : 'design-1', implementedWorkspaceRevisionId: hasImplementation ? 'workspace-2' : null, currentVerificationRunId: null, repairCycle: 0, maxRepairCycles: 2 }, workspace: { owner: 'conductor', key: 'mission-1', state: 'ready', source: { kind: 'agent_workspace', agentId: 'agent-1', agentUpdatedAt: time }, currentRevisionId: hasImplementation ? 'workspace-2' : 'workspace-1', revisionStatus: 'clean', nextRevisionSequence: 3 }, currentTaskId: hasImplementation ? null : 'task-1', nextEventSequence: 1, activeRecoveryCommandId: null, tokenBudget: null, createdAt: time, updatedAt: time, startedAt: time, completedAt: phase === 'completed' ? time : null }; }
function task(stage: MissionTask['stage'], status: MissionTask['status']): MissionTask { return { id: 'task-1', missionId: 'mission-1', order: 0, stage, assignedAgentId: 'agent-1', title: stage, instruction: stage, inputDesignRevisionId: stage === 'design' ? null : 'design-1', inputVerificationRunId: stage === 'repair' ? 'verify-1' : null, inputWorkspaceRevisionId: stage === 'repair' ? 'workspace-2' : 'workspace-1', repairCycle: stage === 'repair' ? 1 : null, status, authoritativeAttemptId: status === 'running' || status === 'failed' ? 'attempt-1' : null, authorityVersion: status === 'running' || status === 'failed' ? 1 : 0, inputArtifactIds: [], outputArtifactIds: [], outputWorkspaceRevisionId: null, createdAt: time, updatedAt: time, startedAt: null, completedAt: null }; }
function attempt(stage: MissionTask['stage'], status: TaskAttempt['status']): TaskAttempt { return { id: 'attempt-1', missionId: 'mission-1', taskId: 'task-1', agentId: 'agent-1', attemptNumber: 1, authorityVersion: 1, stage, inputDesignRevisionId: stage === 'design' ? null : 'design-1', inputVerificationRunId: stage === 'repair' ? 'verify-1' : null, inputWorkspaceRevisionId: stage === 'repair' ? 'workspace-2' : 'workspace-1', repairCycle: stage === 'repair' ? 1 : null, status, runId: 'run-1', runtimeThreadId: null, inputArtifactIds: [], outputArtifactId: null, outputWorkspaceRevisionId: null, usage: null, error: status === 'failed' ? { category: 'agent', message: 'Design contract was invalid' } : null, supersededAt: null, supersededByAttemptId: null, startedByRecoveryCommandId: null, createdAt: time, startedAt: time, completedAt: status === 'running' ? null : time, updatedAt: time }; }
function verification(status: VerificationRun['status'], id = 'verify-1'): VerificationRun { return { id, missionId: 'mission-1', designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2', cycle: id === 'verify-1' ? 0 : 1, status, correlationId: `correlation-${id}`, checks: status === 'failed' ? [{ id: 'check-1', kind: 'interaction', label: 'Save button', passed: false, details: 'expected state missing' }] : status === 'passed' ? [{ id: 'check-1', kind: 'runtime', label: 'Runtime', passed: true, details: 'passed' }] : [], consoleErrors: [], pageErrors: [], url: null, durationMs: 10, referenceScreenshotArtifactId: null, actualScreenshotArtifactId: null, reportArtifactId: null, visualDifference: null, error: status === 'error' ? { category: 'infrastructure', message: 'browser unavailable' } : null, createdAt: time, startedAt: time, completedAt: ['passed', 'failed', 'error'].includes(status) ? time : null, updatedAt: time }; }
function event(type: MissionEvent['type'], details: MissionEvent['details'], actor: MissionEvent['actor'] = 'system'): MissionEvent { return { id: `${type}-${Math.random()}`, missionId: 'mission-1', sequence: 1, type, taskId: null, attemptId: null, agentId: null, actor, details, createdAt: time }; }
function precheckEvent(run: VerificationRun): MissionEvent { return event('implementation_precheck_passed', { verificationRunId: run.id, designRevisionId: run.designRevisionId, workspaceRevisionId: run.workspaceRevisionId }); }
function acceptanceEvent(precheck: VerificationRun): MissionEvent { return event('implementation_review_accepted', { precheckVerificationRunId: precheck.id, designRevisionId: precheck.designRevisionId, workspaceRevisionId: precheck.workspaceRevisionId }, 'human'); }
function project(current: Mission, tasks: MissionTask[] = [], attempts: TaskAttempt[] = [], runs: VerificationRun[] = [], events: MissionEvent[] = [], capabilities = recovery(), implementationAdmission: ImplementationAdmissionView = current.workflow.phase === 'implementing' ? readyAdmission : unavailableAdmission) { return projectMissionProduct({ mission: current, tasks, attempts, designRevisions: [], verificationRuns: runs, events, recovery: capabilities, implementationAdmission, workspaceState: 'clean' }); }

describe('Mission product projection', () => {
  it.each([
    ['pending Design', project(mission('designing', 'pending'), [task('design', 'pending')]), 'Ready to prepare design', 'generate_design'],
    ['running Design', project(mission('designing', 'running'), [task('design', 'running')], [attempt('design', 'running')]), 'Preparing design', null],
    ['approval', project(mission('awaiting_approval', 'paused')), 'Review the proposed design', 'approve_design'],
    ['pending Build', project(mission('implementing', 'paused'), [task('implement', 'pending')]), 'Ready to build', 'run_builder'],
    ['running Build', project(mission('implementing', 'running'), [task('implement', 'running')], [attempt('implement', 'running')]), 'Building the approved design', null],
    ['automatic check fallback', project(mission('verifying', 'paused'), [], [], [], [], recovery({ verificationAdmission: { accepted: true, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2' } })), 'Builder finished — checking the app', 'start_verification'],
    ['precheck running', (() => { const current = mission('verifying', 'running'); const run = verification('running'); current.workflow.currentVerificationRunId = run.id; return project(current, [], [], [run]); })(), 'Checking the built app', null],
  ])('%s maps to the authoritative state and CTA', (_name, result, headline, action) => { expect(result.headline).toBe(headline); expect(result.primaryAction?.id ?? null).toBe(action); expect(result.rail.filter((step) => step.state === 'current')).toHaveLength(1); });

  it('projects precheck PASS as built-result review instead of completion', () => { const current = mission('verifying', 'paused'); const run = verification('passed'); current.workflow.currentVerificationRunId = run.id; const result = project(current, [], [], [run], [precheckEvent(run)]); expect(result).toMatchObject({ state: 'implementation_review', currentStage: 'review', headline: 'Review the built result', completionAuthority: 'pending', primaryAction: { id: 'accept_implementation' }, implementationReview: { precheckVerificationRunId: run.id, accepted: false, canRequestChanges: true } }); });

  it('projects final verification only after the exact implementation acceptance event', () => { const precheck = verification('passed'); const finalRun = verification('running', 'verify-2'); const current = mission('verifying', 'running'); current.workflow.currentVerificationRunId = finalRun.id; const result = project(current, [], [], [precheck, finalRun], [precheckEvent(precheck), acceptanceEvent(precheck)]); expect(result).toMatchObject({ state: 'verifying', currentStage: 'verify', headline: 'Final check in progress', completionAuthority: 'pending', implementationReview: { accepted: true } }); });

  it.each([
    ['workspace_changed', 'The Mission workspace changed after the approved checkpoint.'],
    ['agent_not_ready', 'The assigned Builder is not currently ready.'],
    ['budget_exhausted', 'The Mission token budget is exhausted.'],
    ['reference_integrity_failed', 'The protected DesignRevision reference could not be verified.'],
  ] as const)('keeps approval valid but blocks Builder for %s', (reason, message) => { const result = project(mission('implementing', 'paused'), [task('implement', 'pending')], [], [], [], recovery(), { allowed: false, reason, message }); expect(result).toMatchObject({ state: 'implementation_blocked', headline: 'Build blocked', implementationLock: 'unlocked', completionAuthority: 'pending', primaryAction: null, implementationAdmission: { allowed: false, reason } }); expect(result.explanation).toBe(message); });

  it('offers deterministic finalization instead of rerunning a Builder whose AgentRun already completed', () => { const current = mission('implementing', 'recovered_paused'); current.workspace.revisionStatus = 'uncheckpointed'; const implementationTask = task('implement', 'failed'); const failedAttempt = { ...attempt('implement', 'failed'), error: { category: 'infrastructure', message: 'Workspace contains a non-regular entry: node_modules/.bin/esbuild' } }; const result = project(current, [implementationTask], [failedAttempt], [], [], recovery({ resumeImplementation: { allowed: true, taskId: implementationTask.id, attemptId: failedAttempt.id, runId: 'run-1', inputWorkspaceRevisionId: 'workspace-1', designRevisionId: 'design-1' } }), { allowed: false, reason: 'workspace_changed', message: 'The Mission workspace changed after the approved checkpoint.' }); expect(result).toMatchObject({ state: 'implementation_blocked', headline: 'Builder finished — save the result', implementationLock: 'unlocked', completionAuthority: 'pending', primaryAction: { id: 'finalize_build' } }); expect(result.explanation).toContain('does not rerun the Builder'); });

  it('projects pending and running Repair explicitly', () => { const pendingMission = mission('repairing', 'paused'); pendingMission.currentTaskId = 'task-1'; pendingMission.workflow.currentVerificationRunId = 'verify-1'; pendingMission.workflow.repairCycle = 1; expect(project(pendingMission, [task('repair', 'pending')])).toMatchObject({ state: 'repairing', headline: 'Repair ready', primaryAction: { id: 'run_repair' } }); const runningMission = { ...pendingMission, status: 'running' as const }; expect(project(runningMission, [task('repair', 'running')], [attempt('repair', 'running')])).toMatchObject({ headline: 'Fixing the built result', primaryAction: null }); });

  it('projects failed Design retry from server recovery truth', () => { const current = mission('designing', 'paused'); const currentTask = task('design', 'failed'); const failedAttempt = attempt('design', 'failed'); const result = project(current, [currentTask], [failedAttempt], [], [], recovery({ retryCurrentDesign: { allowed: true, taskId: currentTask.id, attemptId: failedAttempt.id, inputWorkspaceRevisionId: 'workspace-1' } })); expect(result.primaryAction?.id).toBe('retry_design'); expect(result.failure).toMatchObject({ category: 'agent', message: 'Design contract was invalid' }); });
  it('explains a failed Design when the server retry limit denies another attempt', () => { const current = mission('designing', 'paused'); const result = project(current, [task('design', 'failed')], [attempt('design', 'failed')], [], [], recovery({ retryCurrentDesign: { allowed: false, reason: 'Design retry limit reached.' } })); expect(result).toMatchObject({ headline: 'Design needs attention', primaryAction: null, completionAuthority: 'pending' }); expect(result.explanation).toContain('Design retry limit reached.'); });
  it('projects a stopped Mission truthfully instead of as an active Design stage', () => { const current = mission('designing', 'cancelled'); const result = project(current, [task('design', 'cancelled')]); expect(result).toMatchObject({ state: 'stopped', headline: 'Mission stopped', implementationLock: 'locked', completionAuthority: 'pending', primaryAction: null }); });

  it('distinguishes precheck ERROR, semantic FAIL after auto Repair, and historical exact PASS', () => {
    const errorMission = mission('verifying', 'paused'); const errorRun = verification('error'); errorMission.workflow.currentVerificationRunId = errorRun.id; const errorView = project(errorMission, [], [], [errorRun], [], recovery({ retryVerification: { allowed: true, verificationRunId: errorRun.id, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2' }, verificationAdmission: { accepted: true, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2' } })); expect(errorView).toMatchObject({ headline: 'App check could not run', completionAuthority: 'pending', primaryAction: { id: 'retry_verification' } });
    const failedMission = mission('awaiting_intervention', 'blocked'); const failedRun = verification('failed'); failedMission.workflow.currentVerificationRunId = failedRun.id; failedMission.workflow.repairCycle = 1; const automaticRepair = event('repair_scheduled', { trigger: 'automatic_precheck', verificationRunId: 'verify-0' }); const failedView = project(failedMission, [], [], [failedRun], [automaticRepair]); expect(failedView).toMatchObject({ headline: 'Built app needs changes', completionAuthority: 'denied', primaryAction: null, implementationReview: { canRequestChanges: true } }); expect(failedView.explanation).toContain('one remaining repair');
    const exhaustedMission = { ...failedMission, workflow: { ...failedMission.workflow, repairCycle: 2 } }; const exhaustedView = project(exhaustedMission, [], [], [failedRun], [automaticRepair]); expect(exhaustedView).toMatchObject({ completionAuthority: 'denied', primaryAction: null, implementationReview: { canRequestChanges: false } }); expect(exhaustedView.explanation).toContain('allowed repair attempts are exhausted');
    const completed = mission('completed', 'completed'); const passedRun = verification('passed'); completed.workflow.currentVerificationRunId = passedRun.id; expect(project(completed, [], [], [passedRun])).toMatchObject({ headline: 'Verified and complete', completionAuthority: 'authorized' }); expect(project(completed, [], [], [])).toMatchObject({ state: 'degraded', completionAuthority: 'pending' });
  });
});
