import { describe, expect, it } from 'vitest';
import { deriveMissionRecoveryCapabilities, type MissionRecoveryFacts } from './mission-recovery-policy.js';
import type { Agent, AgentRun, Mission, MissionTask, MissionWorkspaceRevision, TaskAttempt, VerificationRun } from './types.js';

const time = '2026-01-01T00:00:00.000Z';
function facts(): MissionRecoveryFacts {
  const agent: Agent = { id: 'agent-1', name: 'Designer', description: '', instructions: '', status: 'ready', workspacePath: '/agent', codexThreadId: null, lastError: null, createdAt: time, updatedAt: time };
  const mission: Mission = { id: 'mission-1', goal: 'goal', status: 'paused', participants: [{ agentId: agent.id, order: 0, snapshot: { name: agent.name, description: '', instructions: '', agentUpdatedAt: time } }], workflow: { phase: 'designing', designerAgentId: agent.id, builderAgentId: agent.id, latestDesignRevisionId: null, approvedDesignRevisionId: null, implementedWorkspaceRevisionId: null, currentVerificationRunId: null, repairCycle: 0, maxRepairCycles: 2 }, workspace: { owner: 'conductor', key: 'mission-1', state: 'ready', source: { kind: 'agent_workspace', agentId: agent.id, agentUpdatedAt: time }, currentRevisionId: 'workspace-1', revisionStatus: 'clean', nextRevisionSequence: 2 }, currentTaskId: 'task-1', nextEventSequence: 1, activeRecoveryCommandId: null, tokenBudget: null, createdAt: time, updatedAt: time, startedAt: time, completedAt: null };
  const currentTask: MissionTask = { id: 'task-1', missionId: mission.id, order: 0, stage: 'design', assignedAgentId: agent.id, title: 'Design', instruction: 'design', inputDesignRevisionId: null, inputVerificationRunId: null, inputWorkspaceRevisionId: 'workspace-1', repairCycle: null, status: 'failed', authoritativeAttemptId: 'attempt-1', authorityVersion: 1, inputArtifactIds: [], outputArtifactIds: [], outputWorkspaceRevisionId: null, createdAt: time, updatedAt: time, startedAt: time, completedAt: time };
  const attempt: TaskAttempt = { id: 'attempt-1', missionId: mission.id, taskId: currentTask.id, agentId: agent.id, attemptNumber: 1, authorityVersion: 1, stage: 'design', inputDesignRevisionId: null, inputVerificationRunId: null, inputWorkspaceRevisionId: 'workspace-1', repairCycle: null, status: 'failed', runId: 'run-1', runtimeThreadId: null, inputArtifactIds: [], outputArtifactId: null, outputWorkspaceRevisionId: null, usage: null, error: { category: 'agent', message: 'invalid design' }, supersededAt: null, supersededByAttemptId: null, startedByRecoveryCommandId: null, createdAt: time, startedAt: time, completedAt: time, updatedAt: time };
  const run: AgentRun = { id: 'run-1', agentId: agent.id, status: 'failed', prompt: 'design', output: null, error: 'invalid design', usage: null, startedAt: time, completedAt: time, createdAt: time, context: { kind: 'mission', missionId: mission.id, taskId: currentTask.id, attemptId: attempt.id } };
  const workspaceRevision: MissionWorkspaceRevision = { id: 'workspace-1', missionId: mission.id, sequence: 1, parentRevisionId: null, restoredFromRevisionId: null, snapshotKey: 'revision-workspace-1', contentHash: 'a'.repeat(64), origin: 'mission_start', boundaries: [{ kind: 'before_task', taskId: currentTask.id }], taskId: currentTask.id, attemptId: null, interventionArtifactId: null, createdBy: 'system', createdAt: time };
  return { missions: [mission], mission, currentTask, attempts: [attempt], runs: [run], currentVerification: null, workspaceRevision, workspaceState: 'clean', assignedAgent: agent, measuredTokens: 0, activeCommand: null };
}

describe('Mission recovery capability policy', () => {
  it('allows only an exact failed Design retry and closes on limits, budget, running work, or unavailable Agent', () => { const base = facts(); expect(deriveMissionRecoveryCapabilities(base).retryCurrentDesign).toMatchObject({ allowed: true, taskId: 'task-1', attemptId: 'attempt-1', inputWorkspaceRevisionId: 'workspace-1' }); const extra = (number: number): TaskAttempt => ({ ...base.attempts[0]!, id: `attempt-${number}`, attemptNumber: number, authorityVersion: number }); expect(deriveMissionRecoveryCapabilities({ ...base, attempts: [base.attempts[0]!, extra(2), extra(3)] }).retryCurrentDesign).toMatchObject({ allowed: false, reason: 'Design retry limit reached.' }); expect(deriveMissionRecoveryCapabilities({ ...base, mission: { ...base.mission, tokenBudget: 10 }, measuredTokens: 10 }).retryCurrentDesign).toMatchObject({ allowed: false, reason: 'Mission token budget is exhausted.' }); expect(deriveMissionRecoveryCapabilities({ ...base, assignedAgent: { ...base.assignedAgent!, status: 'busy' } }).retryCurrentDesign.allowed).toBe(false); expect(deriveMissionRecoveryCapabilities({ ...base, attempts: [{ ...base.attempts[0]!, status: 'running' }], currentTask: { ...base.currentTask!, status: 'running' } }).retryCurrentDesign.allowed).toBe(false); });

  it('allows deterministic Builder finalization only when the AgentRun already completed and exact bindings remain current', () => {
    const base = facts();
    const mission: Mission = { ...base.mission, status: 'recovered_paused', workflow: { ...base.mission.workflow, phase: 'implementing', latestDesignRevisionId: 'design-1', approvedDesignRevisionId: 'design-1' }, workspace: { ...base.mission.workspace, revisionStatus: 'uncheckpointed' } };
    const task: MissionTask = { ...base.currentTask!, stage: 'implement', title: 'Implement', instruction: 'implement', inputDesignRevisionId: 'design-1', status: 'failed' };
    const attempt: TaskAttempt = { ...base.attempts[0]!, stage: 'implement', inputDesignRevisionId: 'design-1', error: { category: 'infrastructure', message: 'checkpoint capture failed' } };
    const run: AgentRun = { ...base.runs[0]!, status: 'completed', prompt: 'implement', output: 'Builder completed.', error: null, context: { kind: 'mission', missionId: mission.id, taskId: task.id, attemptId: attempt.id } };
    const recoveryFacts: MissionRecoveryFacts = { ...base, mission, missions: [mission], currentTask: task, attempts: [attempt], runs: [run], workspaceState: 'unavailable' };
    expect(deriveMissionRecoveryCapabilities(recoveryFacts).resumeImplementation).toMatchObject({ allowed: true, taskId: task.id, attemptId: attempt.id, runId: run.id, inputWorkspaceRevisionId: 'workspace-1', designRevisionId: 'design-1' });
    expect(deriveMissionRecoveryCapabilities({ ...recoveryFacts, runs: [{ ...run, status: 'failed', error: 'runtime failed' }] }).resumeImplementation.allowed).toBe(false);
    expect(deriveMissionRecoveryCapabilities({ ...recoveryFacts, mission: { ...mission, workspace: { ...mission.workspace, revisionStatus: 'clean' } } }).resumeImplementation.allowed).toBe(false);
  });

  it('allows verification retry only for an exact infrastructure ERROR binding', () => { const base = facts(); const mission = { ...base.mission, status: 'paused' as const, currentTaskId: null, workflow: { ...base.mission.workflow, phase: 'verifying' as const, approvedDesignRevisionId: 'design-1', implementedWorkspaceRevisionId: 'workspace-2', currentVerificationRunId: 'verify-1' }, workspace: { ...base.mission.workspace, currentRevisionId: 'workspace-2' } }; const run: VerificationRun = { id: 'verify-1', missionId: mission.id, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2', cycle: 0, status: 'error', correlationId: 'correlation', checks: [], consoleErrors: [], pageErrors: [], url: null, durationMs: 1, referenceScreenshotArtifactId: null, actualScreenshotArtifactId: null, reportArtifactId: null, visualDifference: null, error: { category: 'infrastructure', message: 'browser unavailable' }, createdAt: time, startedAt: time, completedAt: time, updatedAt: time }; const capability = deriveMissionRecoveryCapabilities({ ...base, mission, missions: [mission], currentTask: null, currentVerification: run, workspaceRevision: { ...base.workspaceRevision!, id: 'workspace-2' } }); expect(capability.retryVerification).toMatchObject({ allowed: true, verificationRunId: run.id, designRevisionId: 'design-1', workspaceRevisionId: 'workspace-2' }); const failed = { ...run, status: 'failed' as const, error: null }; expect(deriveMissionRecoveryCapabilities({ ...base, mission: { ...mission, status: 'blocked', workflow: { ...mission.workflow, phase: 'awaiting_intervention' } }, currentTask: null, currentVerification: failed, workspaceRevision: { ...base.workspaceRevision!, id: 'workspace-2' } }).retryVerification.allowed).toBe(false); });
});