import { describe, expect, it } from 'vitest';
import { acceptMissionResult, interruptMissionAttempt, prepareMissionTaskRetry, startMissionAttempt } from './mission-state.js';
import type { Agent, AgentRun, Mission, MissionTask, TaskAttempt } from './types.js';

const time = '2026-01-01T00:00:00.000Z';
function fixture() {
  const agent: Agent = { id: 'agent-1', name: 'Designer', description: '', instructions: '', status: 'ready', workspacePath: '/agent-1', codexThreadId: null, lastError: null, createdAt: time, updatedAt: time };
  const mission: Mission = { id: 'mission-1', goal: 'goal', status: 'pending', participants: [{ agentId: agent.id, order: 0, snapshot: { name: agent.name, description: '', instructions: '', agentUpdatedAt: time } }], workflow: { phase: 'designing', designerAgentId: agent.id, builderAgentId: agent.id, latestDesignRevisionId: null, approvedDesignRevisionId: null, implementedWorkspaceRevisionId: null, currentVerificationRunId: null, repairCycle: 0, maxRepairCycles: 2 }, workspace: { owner: 'conductor', key: 'mission-1', state: 'ready', source: { kind: 'agent_workspace', agentId: agent.id, agentUpdatedAt: time }, currentRevisionId: 'workspace-1', revisionStatus: 'clean', nextRevisionSequence: 2 }, currentTaskId: 'task-1', nextEventSequence: 1, activeRecoveryCommandId: null, tokenBudget: null, createdAt: time, updatedAt: time, startedAt: null, completedAt: null };
  const task: MissionTask = { id: 'task-1', missionId: mission.id, order: 0, stage: 'design', assignedAgentId: agent.id, title: 'Design', instruction: 'design', inputDesignRevisionId: null, inputVerificationRunId: null, inputWorkspaceRevisionId: 'workspace-1', repairCycle: null, status: 'pending', authoritativeAttemptId: null, authorityVersion: 0, inputArtifactIds: [], outputArtifactIds: [], outputWorkspaceRevisionId: null, createdAt: time, updatedAt: time, startedAt: null, completedAt: null };
  return { agent, mission, task };
}

describe('Mission attempt authority', () => {
  it('binds an attempt to stage inputs and rejects a stale result', () => { const records = fixture(); const run: AgentRun = { id: 'run-1', agentId: records.agent.id, status: 'queued', prompt: 'design', output: null, error: null, usage: null, startedAt: null, completedAt: null, createdAt: time, context: { kind: 'mission', missionId: records.mission.id, taskId: records.task.id, attemptId: 'pending' } }; const decision = startMissionAttempt({ missions: [records.mission], mission: records.mission, task: records.task, agent: records.agent, inputArtifactIds: [], missionArtifactIds: [], attempts: [], authoritativeAttempt: null, authoritativeRun: null, run, attemptId: 'attempt-1', timestamp: time, tokenBudget: null }); expect(decision.kind).toBe('admitted'); if (decision.kind !== 'admitted') return; expect(decision.attempt).toMatchObject({ stage: 'design', inputWorkspaceRevisionId: 'workspace-1' }); const terminalRun = { ...decision.run, status: 'completed' as const }; expect(acceptMissionResult(decision.task, decision.attempt, terminalRun, { mission: decision.mission })).toEqual({ accepted: true }); const staleTask = { ...decision.task, authorityVersion: decision.task.authorityVersion + 1 }; expect(acceptMissionResult(staleTask, decision.attempt, terminalRun)).toEqual({ accepted: false, reason: 'attempt_not_authoritative' }); });
  it('interrupts active work and revokes task authority without inventing completion', () => { const records = fixture(); const run: AgentRun = { id: 'run-1', agentId: records.agent.id, status: 'running', prompt: 'design', output: null, error: null, usage: null, startedAt: time, completedAt: null, createdAt: time, context: { kind: 'mission', missionId: records.mission.id, taskId: records.task.id, attemptId: 'attempt-1' } }; const started = startMissionAttempt({ missions: [records.mission], mission: records.mission, task: records.task, agent: records.agent, inputArtifactIds: [], missionArtifactIds: [], attempts: [], authoritativeAttempt: null, authoritativeRun: null, run, attemptId: 'attempt-1', timestamp: time, tokenBudget: null }); expect(started.kind).toBe('admitted'); if (started.kind !== 'admitted') return; const interrupted = interruptMissionAttempt({ mission: started.mission, task: started.task, attempt: started.attempt, run: started.run, timestamp: time }); expect(interrupted.mission.status).toBe('recovered_paused'); expect(interrupted.task?.authoritativeAttemptId).toBeNull(); expect(interrupted.task?.authorityVersion).toBe(interrupted.attempt.authorityVersion + 1); expect(interrupted.task?.status).toBe('interrupted'); expect(interrupted.attempt.status).toBe('interrupted'); });
  it('prepares a failed Design retry without recycling history and makes the old result stale', () => { const records = fixture(); const attempt: TaskAttempt = { id: 'attempt-1', missionId: records.mission.id, taskId: records.task.id, agentId: records.agent.id, attemptNumber: 1, authorityVersion: 1, stage: 'design', inputDesignRevisionId: null, inputVerificationRunId: null, inputWorkspaceRevisionId: 'workspace-1', repairCycle: null, status: 'failed', runId: 'run-1', runtimeThreadId: null, inputArtifactIds: [], outputArtifactId: null, outputWorkspaceRevisionId: null, usage: null, error: { category: 'agent', message: 'invalid package' }, supersededAt: null, supersededByAttemptId: null, startedByRecoveryCommandId: null, createdAt: time, startedAt: time, completedAt: time, updatedAt: time }; const task = { ...records.task, status: 'failed' as const, authoritativeAttemptId: attempt.id, authorityVersion: 1 }; const decision = prepareMissionTaskRetry({ mission: { ...records.mission, status: 'paused' }, task, attempt, timestamp: '2026-01-02T00:00:00.000Z' }); expect(decision.accepted).toBe(true); if (!decision.accepted) return; expect(decision.task).toMatchObject({ id: task.id, status: 'pending', authoritativeAttemptId: null, authorityVersion: 1, inputWorkspaceRevisionId: 'workspace-1' }); expect(decision.attempt).toMatchObject({ id: attempt.id, status: 'failed', supersededAt: '2026-01-02T00:00:00.000Z' }); const oldRun: AgentRun = { id: 'run-1', agentId: records.agent.id, status: 'completed', prompt: '', output: '', error: null, usage: null, startedAt: time, completedAt: time, createdAt: time, context: { kind: 'mission', missionId: records.mission.id, taskId: task.id, attemptId: attempt.id } }; expect(acceptMissionResult(decision.task, { ...decision.attempt, status: 'running' }, oldRun)).toEqual({ accepted: false, reason: 'attempt_not_authoritative' }); });
});
